export const ENABLE_DEMO_MODE = "ENABLE_DEMO_MODE"
export const DISABLE_DEMO_MODE = "DISABLE_DEMO_MODE";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

export const FETCH_CAR_DATA_START = "FETCH_CAR_DATA_START";
export const FETCH_CAR_DATA_SUCCESS = "FETCH_CAR_DATA_SUCCESS";
export const FETCH_CAR_DATA_FAILURE = "FETCH_CAR_DATA_FAILURE";

export const FETCH_SH_DATA_START = "FETCH_SH_DATA_START";
export const FETCH_SH_DATA_SUCCESS = "FETCH_SH_DATA_SUCCESS";
export const FETCH_SH_DATA_FAILURE = "FETCH_SH_DATA_FAILURE";

export const FETCH_SERVICE_DATA_START = "FETCH_SERVICE_DATA_START";
export const FETCH_SERVICE_DATA_SUCCESS = "FETCH_SERVICE_DATA_SUCCESS";
export const FETCH_SERVICE_DATA_FAILURE = "FETCH_SERVICE_DATA_FAILURE";

export const FETCH_LOCATION_DATA_START = "FETCH_LOCATION_DATA_START";
export const FETCH_LOCATION_DATA_SUCCESS = "FETCH_LOCATION_DATA";
export const FETCH_LOCATION_DATA_FAILURE = "FETCH_LOCATION_DATA_FAILURE";

export const MODIFY_CAR_DATA_START = "MODIFY_CAR_DATA_START";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const MODIFY_CAR_DATA_FAILURE = "MODIFY_CAR_DATA_FAILURE";

export const MODIFY_SERVICE_HISTORY_START = "MODIFY_SERVICE_HISTORY_START";
export const EDIT_SERVICE_RECORD_SUCCESS = "EDIT_SERVICE_RECORD_SUCCESS";
export const ADD_SERVICE_RECORD_SUCCESS = "ADD_SERVICE_RECORD_SUCCESS";
export const DELETE_SERVICE_RECORD_SUCCESS = "DELETE_SERVICE_RECORD_SUCCESS";
export const MODIFY_SERVICE_HISTORY_FAILURE = "MODIFY_SERVICE_HISTORY_FAILURE";

export const MODIFY_SERVICE_DATA_START = "MODIFY_SERVICE_DATA_START";
export const DELETE_SERVICE_DATA_SUCCESS = "DELETE_SERVICE_DATA_SUCCESS";
export const MODIFY_SERVICE_DATA_FAILURE = "MODIFY_SERVICE_DATA_FAILURE";

export const MODIFY_LOCATION_DATA_START = "MODIFY_LOCATION_DATA_START";
export const DELETE_LOCATION_DATA_SUCCESS = "DELETE_LOCATION_DATA_SUCCESS";
export const MODIFY_LOCATION_DATA_FAILURE = "MODIFY_LOCATION_DATA_FAILURE";

export const DISCONNECT_ACCOUNT = "DISCONNECT_ACCOUNT";
export const DISCONNECT_ACCOUNT_FAILURE = "DISCONNECT_ACCOUNT_FAILURE"
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";