export const GET_USER_DATA = "GET_USER_DATA";
export const GET_CAR_DATA = "GET_CAR_DATA";
export const GET_SH_DATA = "GET_SH_DATA";
export const GET_SERVICE_DATA = "GET_SERVICE_DATA";
export const GET_LOCATION_DATA = "GET_LOCATION_DATA";

export const MODIFY_CAR_DATA_START = "MODIFY_CAR_DATA_START";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const MODIFY_CAR_DATA_FAILURE = "MODIFY_CAR_DATA_FAILURE";

export const MODIFY_SERVICE_HISTORY_START = "MODIFY_SERVICE_HISTORY_START";
export const EDIT_SERVICE_RECORD_SUCCESS = "EDIT_SERVICE_RECORD_SUCCESS";
export const ADD_SERVICE_RECORD_SUCCESS = "ADD_SERVICE_RECORD_SUCCESS";
export const DELETE_SERVICE_RECORD_SUCCESS = "DELETE_SERVICE_RECORD_SUCCESS";
export const MODIFY_SERVICE_HISTORY_FAILURE = "MODIFY_SERVICE_HISTORY_FAILURE";

export const MODIFY_SERVICE_DATA_START = "MODIFY_SERVICE_DATA_START";
export const DELETE_SERVICE_DATA_SUCCESS = "DELETE_SERVICE_DATA_SUCCESS";
export const MODIFY_SERVICE_DATA_FAILURE = "MODIFY_SERVICE_DATA_FAILURE";

export const MODIFY_LOCATION_DATA_START = "MODIFY_LOCATION_DATA_START";
export const DELETE_LOCATION_DATA_SUCCESS = "DELETE_LOCATION_DATA_SUCCESS";
export const MODIFY_LOCATION_DATA_FAILURE = "MODIFY_LOCATION_DATA_FAILURE";

export const DISCONNECT_ACCOUNT = "DISCONNECT_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";